services:
  SPlayer:
    build:
      context: .
    image: splayer
    container_name: SPlayer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 25884:25884
    restart: always
